#!/bin/sh
cd "$(dirname "$0")"
UNICODE_VERSION="${1:-16.0.0}"
mkdir -p "public/charts/$UNICODE_VERSION"
curl -o "public/charts/$UNICODE_VERSION/CodeCharts.pdf.tmp" "https://www.unicode.org/Public/$UNICODE_VERSION/charts/CodeCharts.pdf"
mv "public/charts/$UNICODE_VERSION/CodeCharts.pdf.tmp" "public/charts/$UNICODE_VERSION/CodeCharts.pdf"
